# Generated by Django 3.2.9 on 2021-11-18 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import post.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('caption', models.TextField(verbose_name='Caption')),
                ('file', models.ImageField(blank=True, max_length=128, null=True, upload_to=post.models.get_file_path, verbose_name='Media')),
                ('comment_count', models.PositiveIntegerField(default=0, verbose_name='Total Comment')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='Total Like')),
                ('feed', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Feed')),
                ('like', models.ManyToManyField(related_name='likers', to=settings.AUTH_USER_MODEL, verbose_name='Like')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
