# Generated by Django 3.2.9 on 2021-11-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
        ('post', '0002_auto_20211118_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ManyToManyField(related_name='posts', to='image.Image', verbose_name='Post Images'),
        ),
    ]
