# Generated by Django 3.2.9 on 2021-11-18 06:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('username', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=300, unique=True, verbose_name='Email')),
                ('follower_count', models.PositiveIntegerField(default=0, verbose_name='Total Follower')),
                ('following_count', models.PositiveIntegerField(default=0, verbose_name='Total Following')),
                ('post_count', models.PositiveIntegerField(default=0, verbose_name='Total post')),
                ('follow', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Follow')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
